### ISSUE TITLE
Bug From PILLOW? Integer Overflow

### ISSUE THREAD

**Issue by CielAl** [choosehappy/PytorchUnet#1]
For data sets occasionally containing slides with too many regions or area > 4-byte INT_MAX, a runtime error will be reported from the lower level operations on PILs, while using cv2.imread.

**Comment by CielAl** [comment]
It might be necessary to downsample the slides with OpenSlide in prior to the process. Note, the same error will occur if use osh.get_thumbnail directly, which operates with the PIL.

**Comment by choosehappy** [comment]
this code was designed to be used with ROIs that have already been cropped from a WSI image, to reduce both code complexity and improve reproducibility. as you suggest, need to preprocess the large image into just the "interesting" chunks (i.e., no point in having the large white space of the background be apart of the tile set)
